### ISSUE TITLE
Remove version number

### ISSUE THREAD

**Issue by ramanxg** [icssc/peterportal-public-api#145]
In our REST endpoint, every request is made at `/rest/v0/courses/all`. We don't really use versions, so for now let's change this to work with `/rest/courses/all`. 

We should keep the `/rest/v0` working, if there are any other applications using this endpoint, it won't break.

**Comment by ChaseC99** [comment]
I'm a little hesitant about removing versioning.... if we do this, any changes to our existing endpoints, parameters, responses, etc could potentially break client side applications.

**Comment by ramanxg** [comment]
> I'm a little hesitant about removing versioning.... if we do this, any changes to our existing endpoints, parameters, responses, etc could potentially break client side applications.

I agree. I was suggesting to keep the v0 endpoints to continue working. We only use version numbers for rest endpoints. so we can continue that, and just also let rest/courses... to work as well.

**Comment by ecxyzzy** [comment]
I'm personally a fan of strongly/semantically versioned APIs, just because it's a guarantee on our part that the API will only change in a breaking way iff the major version is also bumped.

Instead of removing the version number altogether once we hit v1: What if we kept v0 around indefinitely so existing applications won't break, but could begin migrating to v1, which must be stable? Keeping v0 around would also allow us (and any brave early adopters) to test out any new endpoints/features before mainlining them into v1 (or any later version if we do end up implementing breaking changes), since [item 4 of the SemVer spec](https://semver.org/#spec-item-4) states that major version zero should always be considered unstable.

This might also extend to the GraphQL API (currently undecided), even though their best practices state that GraphQL APIs should be versionless, since I personally think their strategy of ["always avoiding breaking changes"](https://graphql.org/learn/best-practices/#versioning) is a bit unrealistic.

Would love to hear your thoughts!

cc: @ramanxg @ChaseC99

**Comment by ChaseC99** [comment]
On the note of GraphQL, I think we could probably get away with not having versions. 

The only thing that would cause GraphQL to break is if you rename or delete existing fields. New fields and objects can always be added without breaking the API.

In the future, if you ever need to significantly change the structure of the API, you could just add a version number at that point moving forward.

**Comment by ramanxg** [comment]
Just to clarify, so the suggestion we move to v1, and then keep v0 for existing applications, as well as using v0 for unstable/testing purposes? I like that idea, and it definitely helps to have those outside of us test the API.

**Comment by ecxyzzy** [comment]
Yup that's what I was going for. Sorry for the belated response, had some IRL tasks to sort out and kinda forgot about this :sweat_smile:

I'll be closing this issue then, and creating one with the goals set forth in the discussion of this one.
