### ISSUE TITLE
Endpoint to Query Batch of Courses

### ISSUE THREAD

**Issue by chenaaron3** [icssc/peterportal-public-api#152]
When we save courses from Peter's Roadmap to the cloud, we only store the id of the courses to save space and to ensure users are not storing old data. We need an endpoint to query all the courses listed in a roadmap. The current solution is to make a separate request for each course, but a batch query would be much preferred.

**Comment by ramanxg** [comment]
To add this feature, let's add it to the allCourses endpoint as a parameter. 

- [ ] In REST add a parameter to the endpoint. If the parameter exists we filter out by the courses listed, otherwise return all courses
- [ ] In GraphQL, allCourses can take an array of courses as an argument. and do the same as above.

**Comment by ramanxg** [comment]
GraphQL is cool. If we want to request multiple courses, it's able to do so by using aliases to rename the result of a field. Here's an example. 
```
query {
  COMPSCI161: course(id: "COMPSCI161"){
    title
    description
    department_name
  }
  COMPSCI163: course(id: "COMPSCI163"){
    title
    description
    department_name
  }
}
```
