### ISSUE TITLE
Implement endpoint to scrape EaterEvals data

### ISSUE THREAD

**Issue by uci-mars** [icssc/peterportal-public-api#16]
PeterPortal wants to display EaterEvals data on the core client. This issue requires prior research and planning.

`/eval`

**Comment by ChaseC99** [comment]
Should we fetch this info on-the-fly or should we download it all and build out a cache?

**Comment by uci-mars** [comment]
Without looking at the problem, I would say depends on the situation.

I would want to avoid caching if possible, since that would add to our maintenance workflow.. If it is as easy to fetch as WebSoC, without needing to scrape the whole HTML document than I would prefer to fetch thais info on-the-fly.

If that isn't an option and we need to scrape an entire page to get the evals, then we can build out a cache.

**Comment by ecxyzzy** [comment]
Closing as this is infeasible for now. We would have to scrape EaterEvals since the evaluation IDs have no correlation with course information (department/course number, etc.), and OIT has stated (as per the following email) that scraping EaterEvals directly would be in violation of Academic Senate policy.

> Thank you for reaching out to us. Unfortunately the use case you've presented is something we do not support. UCI Senate Policy requires that a valid UCInetID that passes authentication be in place for access to EaterEvals. Allowing access to EaterEvals’ results without that authentication would violate policy.
Evaluations data is sensitive information and is provided to students via EaterEvals thanks to approval from the Academic Senate that includes specific conditions including UCInetID authentication and presentation in EaterEvals. Using EaterEvals data outside of the system would violate policy unless it was approved in advance by the Academic Senate's Council on Teaching, Learning, and Student Experience (CTLSE). Therefore we ask you not to scrape EaterEvals without this approval as it would be a violation.

It is _probably_ possible to request permission from the Academic Senate to provide evaluation data directly through the API without going through EaterEvals, but seeing as it is considered "sensitive information" I doubt they would agree, since we would be providing that information without authentication.
