### ISSUE TITLE
Writing Course Codes to Change

### ISSUE THREAD

**Issue by ramanxg** [icssc/peterportal-public-api#209]
![image](https://user-images.githubusercontent.com/9029237/169415219-e907d739-7543-41e5-9177-048b11970c39.png)

**Comment by ramanxg** [comment]
Suggestion: 

Each course has a field `other_name` (draft name) that points to the course it was known previously, or is now known as. 

For WRITING 60: 
```
{
     "other_name" : "WRITING39C"
}
```
In GraphQL, we can map these to another Course Type, so users can get that information, and have the freedom to do what they want with it.

For Grades, we let the website requesting the data, deal with courses being named differently. (Users can make a separate request), or request something like (department: writing, numbers: 39C;60;).

**Comment by ecxyzzy** [comment]
After tinkering with the cache building script I've found some other courses which have been discontinued as of the 2022-23 academic year, and which don't have clearly stated replacements. Additionally, some courses (e.g. INF 171) still have Writing 39C listed as a prerequisite on WebReg, even though "officially" (per the Catalogue) the prerequisite going forwards is Writing 60.

In the interests of data completeness and maintaining backwards compatibility, I think it's best that going forwards that we merge newly generated data with the existing cache, rather than overwriting it wholesale. This will probably be done manually this year, but I'll also look into automating the process, maybe through a GitHub Actions pipeline.
